import { useState } from 'react';
import type { CareerOptions, CareerShortlist, JobApplication, Applicant } from '../../shared/career';
import type { BackgroundFile, BackgroundResult, BackgroundRun, RunAnswer } from '../../shared/background';

export const defaultCareer = (): CareerOptions => ({ boards: [{ provider: 'greenhouse', board: '', region: 'global' }], keywords: '', location: '', maxJobs: 10 });
export const validCareer = (v: CareerOptions) => v.boards.length > 0 && v.boards.every(b => /^[A-Za-z0-9_-]{1,80}$/.test(b.board)) && Number.isInteger(v.maxJobs) && v.maxJobs >= 1 && v.maxJobs <= 20;
export function CareerFields({ value, change }: { value: CareerOptions; change(value: CareerOptions): void }) {
  return <fieldset className="agents-mail-options"><legend>Published job boards</legend>{value.boards.map((board, index) => <div className="agents-form-row" key={index}><label>Provider<select aria-label={`Job provider ${index+1}`} value={board.provider} onChange={e => change({ ...value, boards: value.boards.map((b,i) => i===index ? { ...b, provider: e.target.value as typeof b.provider } : b) })}><option value="greenhouse">Greenhouse</option><option value="lever">Lever</option></select></label><label>Company board token<input aria-label={`Company board ${index+1}`} value={board.board} maxLength={80} required pattern="[A-Za-z0-9_-]+" onChange={e => change({ ...value, boards: value.boards.map((b,i) => i===index ? { ...b, board:e.target.value } : b) })} placeholder="Company token from its board URL" /></label>{board.provider === 'lever' && <label>Lever region<select value={board.region} onChange={e => change({ ...value, boards: value.boards.map((b,i) => i===index ? { ...b, region:e.target.value as typeof b.region } : b) })}><option value="global">Global</option><option value="eu">EU</option></select></label>}{value.boards.length>1 && <button type="button" onClick={() => change({ ...value, boards:value.boards.filter((_b,i)=>i!==index) })}>Remove board</button>}</div>)}<button type="button" disabled={value.boards.length>=4} onClick={() => change({ ...value, boards:[...value.boards,{provider:'greenhouse',board:'',region:'global'}] })}>Add board</button><label>Keywords (all must match title/description)<input aria-label="Job keywords" value={value.keywords} maxLength={120} onChange={e => change({ ...value, keywords:e.target.value })} /></label><label>Location contains<input value={value.location} maxLength={120} onChange={e => change({ ...value, location:e.target.value })} /></label><label>Maximum jobs<input type="number" min="1" max="20" step="1" value={value.maxJobs} onChange={e => change({ ...value, maxJobs:Number(e.target.value) })} /></label><p className="agents-help">Literal filters on public postings. No AI ranking, resume upload or application submission during discovery.</p></fieldset>;
}
export function ShortlistView({ list, run, busy, prepare }: { list: CareerShortlist; run: BackgroundRun; busy: boolean; prepare(input: {runId:string;revision:number;jobKey:string}):void }) {
  return <section className="agents-shortlist"><h3>Career shortlist</h3><p>{list.jobs.length} matches · {list.scanned} jobs scanned{list.truncated ? ' · limits applied; more results may exist' : ''}</p>{!list.jobs.length && <p>No published jobs matched these literal filters.</p>}{list.jobs.map(job => <article className="agents-mail-message" key={job.key}><h4>{job.title}</h4><p>{job.board} · {job.location} · {job.provider}</p><p>{job.description}</p><small>{job.url}</small><button disabled={busy || run.status!=='succeeded'} onClick={() => prepare({runId:run.id,revision:run.revision,jobKey:job.key})}>Prepare application</button></article>)}</section>;
}
export function ApplicationView({ application, run }: { application: JobApplication; run: BackgroundRun }) {
  return <section className="agents-application"><h3>Application review</h3><p><strong>{application.job.title}</strong><br />{application.job.board} · {application.job.location}<br />{application.job.url}</p>{application.applicant && <p>Contact: {application.applicant.firstName} {application.applicant.lastName}<br />{application.applicant.email}<br />{application.applicant.phone}</p>}<p>Frozen resume: {run.inputs[0] || 'Choose a supported PDF'}{application.resume && <><br />{application.resume.bytes.toLocaleString()} bytes<br /><small>SHA-256: {application.resume.hash}</small></>}</p>{application.observation && <><p>Current page: {application.observation.title}<br />{application.observation.url}</p><p>{application.observation.supported ? 'Standard contact fields and PDF resume can be staged.' : 'Manual preparation required; this page is not supported for automatic filling.'}</p><p>Required fields: {application.observation.fields.filter(f=>f.required).map(f=>f.name).join(', ') || 'None detected'}. Review every question yourself; Kite never invents answers.</p><small>Page/fields fingerprint: {application.observation.fingerprint}</small></>}{application.mutation && <p role="status">An external write was attempted at {new Date(application.mutation.at).toLocaleString()}. Submission outcome is uncertain until acknowledged. This run will never be replayed.</p>}{application.receipt && <p>Observed page acknowledgement: {application.receipt.title}<br />{application.receipt.url}<br />{new Date(application.receipt.at).toLocaleString()}. Check employer email/portal for independent confirmation.</p>}</section>;
}
export function ApplicationInput({ run, busy, answer, error }: { run:BackgroundRun;busy:boolean;answer(value:RunAnswer):Promise<void>;error(message:string):void }) {
  const [applicant,setApplicant]=useState<Applicant>({firstName:'',lastName:'',email:'',phone:''}),[files,setFiles]=useState<BackgroundFile[]>([]),[choosing,setChoosing]=useState(false);
  const choose=async()=>{setChoosing(true);try{const result=await window.kite.chooseBackgroundFiles();if(!result.ok) error(result.error);else if(result.files.length!==1||result.files[0].kind!=='pdf') error('Choose one plain PDF resume.');else setFiles(result.files);}catch{error('Resume selection failed.');}finally{setChoosing(false);}};
  return <form className="agents-composer" onSubmit={e=>{e.preventDefault();void answer({runId:run.id,expectedRevision:run.revision,requestId:run.request.id,applicant,fileIds:files.map(f=>f.id)});}}>{(['firstName','lastName','email','phone'] as const).map(key=><label key={key}>{({firstName:'First name',lastName:'Last name',email:'Email',phone:'Phone (optional)'})[key]}<input aria-label={`Applicant ${key}`} type={key==='email'?'email':'text'} maxLength={key==='email'?200:key==='phone'?60:80} required={key!=='phone'} value={applicant[key]} onChange={e=>setApplicant({...applicant,[key]:e.target.value})} /></label>)}<button type="button" disabled={busy||choosing} onClick={()=>{void choose();}}>Choose PDF resume</button><p>{files[0]?.name}</p><button disabled={busy||choosing||files.length!==1} type="submit">Review application inputs</button><p className="agents-help">Your resume is frozen locally. You approve its destination before it enters an application page.</p></form>;
}
export function ApplicationActions({ run, busy, browser, finish, uncertain }: {run:BackgroundRun;busy:boolean;uncertain?:boolean;browser(action:'open'|'check'):Promise<BackgroundResult|undefined>;finish():void}) {
  return <div className="agents-actions"><button disabled={busy} onClick={()=>{void browser('open');}}>Open application browser</button><button disabled={busy} onClick={()=>{void browser('check');}}>{run.request?.kind==='application_review'?'Review current page':'Check acknowledgement'}</button>{run.request?.kind==='application_takeover'&&<button disabled={busy||uncertain} onClick={finish}>Finish preparation without submitting</button>}</div>;
}
