import { useState } from 'react';
import type { MailConnectionState, MailOptions, InboxBriefing } from '../../shared/mail';
import type { BackgroundResult } from '../../shared/background';

export const defaultMail = (): MailOptions => ({ accountId: '', query: 'in:inbox newer_than:7d', maxMessages: 10, includeAttachments: false });
export const validMail = (options: MailOptions) => !!options.accountId && !!options.query.trim() && options.maxMessages >= 1 && options.maxMessages <= 20;
export function MailOptionsFields({ value, onChange, state }: { value: MailOptions; onChange(value: MailOptions): void; state: MailConnectionState | null }) {
  return <fieldset className="agents-mail-options"><legend>Gmail search</legend><label>Account<select aria-label="Mail account" value={value.accountId} onChange={e => onChange({ ...value, accountId: e.target.value })}><option value="">Choose an account</option>{state?.accounts.map(a => <option key={a.id} value={a.id}>{a.email}{a.status !== 'connected' ? ' (reconnect needed)' : ''}</option>)}</select></label><label>Search<input aria-label="Mail search" value={value.query} onChange={e => onChange({ ...value, query: e.target.value })} maxLength={500} required /></label><label>Maximum messages<input type="number" min="1" max="20" step="1" value={value.maxMessages || ''} onChange={e => onChange({ ...value, maxMessages: Number(e.target.value) })} /></label><label className="agents-mail-check"><input type="checkbox" checked={value.includeAttachments} onChange={e => onChange({ ...value, includeAttachments: e.target.checked })} />Save supported document/image attachments too (up to 8 files, 5 MB each, 16 MB total)</label><p className="agents-help">Read-only Gmail access. Briefings use local excerpts; messages are never sent to a model. You review the account and search before each run.</p></fieldset>;
}

export function MailAccounts({ state, refresh }: { state: MailConnectionState | null; refresh(): Promise<void> }) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const action = async (run: () => Promise<BackgroundResult>) => { setBusy(true); setMessage(''); try { const result = await run(); if (result.error) setMessage(result.error); await refresh(); } catch { setMessage('Mail accounts could not be updated.'); } finally { setBusy(false); } };
  return <details className="agents-mail-accounts"><summary>Mail accounts</summary><p>Connect Gmail for local Inbox Briefings. Kite can read/search your selected account and download approved attachments. Sending, drafting, deleting and marking mail as read are unavailable.</p>{!state ? <p role="status">Mail accounts are unavailable. Restart Kite after checking mail storage and OS encryption.</p> : <>
    {!state.configured && <p>A Google Desktop OAuth client is required for this development release. Enable the Gmail API and add your Google account as a consent-screen test user, then import the client JSON.</p>}
    <div className="agents-actions"><button disabled={busy || state.connecting || state.accounts.some(a => a.status !== 'disconnected')} onClick={() => { void action(() => window.kite.configureMail()); }}>{state.configured ? 'Replace Google client' : 'Import Google client'}</button><button disabled={busy || state.connecting || !state.configured} onClick={() => { void action(() => window.kite.connectMail()); }}>Connect Gmail</button>{(state.connecting || busy) && <button onClick={() => { void window.kite.cancelMailConnect(); }}>Cancel connection</button>}</div>
    {state.connecting && <p role="status">Finish signing in through your system browser. The connection expires in five minutes.</p>}
    {state.accounts.map(a => <article className="agents-mail-account" key={a.id}><div><strong>{a.email}</strong><small>{a.status === 'connected' ? 'Connected · read-only Gmail' : a.status === 'disconnected' ? 'Disconnected on this PC' : 'Reconnect needed'}</small></div><button disabled={busy || state.connecting} onClick={() => { void action(() => window.kite.connectMail({ id: a.id, revision: a.revision })); }}>Reconnect</button>{a.status !== 'disconnected' && <button disabled={busy} onClick={() => { void action(() => window.kite.disconnectMail({ id: a.id, revision: a.revision })); }}>Disconnect</button>}</article>)}
    <p className="agents-help">Disconnect stops pending reads and removes local tokens. Existing briefings and exported attachments remain on this PC. Public Gmail availability requires Google's verification; this release does not bundle a verified OAuth client.</p>
  </>}{message && <p role="status">{message}</p>}</details>;
}

export function BriefingView({ briefing, runId, onOpen }: { briefing: InboxBriefing; runId: string; onOpen(runId: string, messageId: string): void }) {
  return <section className="agents-briefing"><h3>Inbox Briefing</h3><p><strong>{briefing.email}</strong><br />Search: {briefing.query}<br />{briefing.messages.length} messages · {new Date(briefing.fetchedAt).toLocaleString()}</p><p className="agents-help">Local excerpts from untrusted source messages. No instructions were executed and no model was called.{briefing.moreMatches ? ' More search matches exist; this run uses your requested limit.' : ''}</p>{!briefing.messages.length && <p>No messages matched this search.</p>}{briefing.messages.map(m => <article className="agents-mail-message" key={m.id}><h4>{m.subject}</h4><p>{m.sender} · {m.receivedAt ? new Date(m.receivedAt).toLocaleString() : 'Unknown date'}</p><pre>{m.excerpt || '(No readable text)'}</pre><small>Message {m.id} · {m.attachments.length} attachments</small><button onClick={() => onOpen(runId, m.id)}>Open source in Gmail</button></article>)}<p>{briefing.selectedAttachments.length} attachments selected; {briefing.skippedAttachments} skipped. Downloads remain untrusted; inspect saved copies before using them.</p></section>;
}
