import { z } from 'zod';
import { defineTool } from '../define';
import { preview, type ToolResult } from '../types';
import { maxTaskSteps, type TaskScope } from '../../../shared/agent';
import { askingPromise, defaultPermissions, type PermissionSettings } from '../../../shared/permissions';
export const taskInput = z.object({ goal: z.string().trim().min(3).max(500), app: z.string().trim().min(1).max(80) }).strict();
export type TaskInput = z.infer<typeof taskInput>;
export function doTask(start: (task: TaskInput, scope: TaskScope) => ToolResult, vision: boolean, permissions: () => PermissionSettings = () => defaultPermissions) {
  return defineTool<TaskInput>({
    name: 'do_task', kind: 'action', approvalRequired: true, inputSchema: taskInput,
    description: `Do a multi-step task for the user inside one app on this computer by operating its controls: clicking buttons, menus and tabs, typing into fields, and pressing shortcuts. Examples: "write a shopping list in Notepad and save it as list.txt", "turn on dark mode in Settings", "search for flights to Goa in Microsoft Edge". Use it only when the user asks you to do something for them. For "how do I…", "show me how…" or "where is…", even about shopping or bookings, use show_me_how instead; never start a task to demonstrate. Errands on the web are tasks too when the user asks you to do them ("buy…", "order…", "book…", "pay my…", "renew…"): shopping, food orders, tickets and bookings, recharges, bills, renewals, subscriptions and online forms. For an errand use app "Microsoft Edge" and the site the user named, else the brand's own store, else a well-known one. Write the goal to stop where the user takes over: a purchase stops at the cart ("find Amul Whey Protein, 60 sachets, on shop.amul.com and add it to the cart"), and the user checks out; a booking, bill or form is filled in up to the payment or final submit. The user always does payment, sign-in and OTPs themselves when Kite hands over, so take on any purchase, booking or bill: never say you can't, and don't open with caveats. Start the task straight away: Kite asks the user during the task when it needs a choice (city, restaurant, size, time, seat). Ask first only for something only the user knows and no site shows, such as which electricity provider or a delivery address. goal: the complete outcome in one sentence, including any exact text to type and file names. app: the app to use, e.g. "Notepad", "Microsoft Edge", "Settings". Kite opens the app if needed, never moves the user's mouse, confirms risky steps with the user, and stops after ${maxTaskSteps} steps. Only call it for a task the user asked for. For "again", "the usual" or "same as last time", use reorder instead, which repeats a remembered order. After calling, reply with one short sentence such as "On it!", or for an errand name the site, such as "Sure, I'll get it from Amul's store in Edge."`,
    summarize: ({ goal, app }) => `Let me do this in ${preview(app, 40)}: "${preview(goal, 120)}"? I'll click and type in ${preview(app, 40)} only, never move your mouse, ${askingPromise(permissions())}, and stop after ${maxTaskSteps} steps.${vision ? ` I may look at its window.` : ''}`,
    execute: async (input, ctx) => { ctx.signal.throwIfAborted(); return start(input, ctx.scope ?? 'task'); },
  });
}
