// Bundled main/preload/React/IPC with only provider traffic redirected to local fixtures.
const {app,BrowserWindow,dialog,session}=require('electron');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const {PDFDocument,StandardFonts}=require('pdf-lib');
const {createCareerFixture}=require('./career-fixture.cjs');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'kite-career-panel-'));app.setPath('userData',root);process.env.KITE_TEST_MODE='1';
app.on('browser-window-created',(_e,w)=>w.setOpacity(0));const errors=[];dialog.showErrorBox=(t,m)=>errors.push(t+': '+m);
const wait=ms=>new Promise(r=>setTimeout(r,ms));const until=async(read,condition,label)=>{for(let i=0;i<250;i++){const v=await read();if(condition(v))return v;await wait(50);}throw Error('Timed out: '+label);};
const evalIn=(w,code)=>w.webContents.executeJavaScript(code);
const click=(w,text)=>evalIn(w,`(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(text)});if(!b||b.disabled)throw Error('Missing/disabled button '+${JSON.stringify(text)});b.click();})()`);
const value=(w,selector,v,event='input')=>evalIn(w,`(()=>{const e=document.querySelector(${JSON.stringify(selector)});Object.getOwnPropertyDescriptor(e.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(v)});e.dispatchEvent(new Event(${JSON.stringify(event)},{bubbles:true}));})()`);
const deadline=setTimeout(()=>{console.error('Career panel timed out');app.exit(1);},60000);
(async()=>{
 const fixture=await createCareerFixture(),nativeFetch=globalThis.fetch.bind(globalThis);
 globalThis.fetch=(url,opt)=>['boards-api.greenhouse.io','api.lever.co','api.eu.lever.co'].includes(new URL(url).hostname)?nativeFetch(fixture.origin+new URL(url).pathname+new URL(url).search,opt):nativeFetch(url,opt);
 const originalPartition=session.fromPartition.bind(session);
 session.fromPartition=(partition,options)=>{const profile=originalPartition(partition,options);if(partition.startsWith('kite-career-'))profile.protocol.handle('https',request=>{const u=new URL(request.url),p=u.pathname.split('/').filter(Boolean),provider=u.hostname.includes('greenhouse')?'greenhouse':'lever';const destination=p.includes('jobs')?`/${provider}/${p[0]}/${p[2]}/apply`:p.length>=3?`/${provider}/${p[0]}/${p[1]}/apply`:u.pathname;return nativeFetch(fixture.origin+destination,{method:request.method,headers:request.headers,...(!['GET','HEAD'].includes(request.method)?{body:request.body,duplex:'half'}:{})});});return profile;};
 const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica);doc.addPage().drawText('Synthetic resume',{x:40,y:700,font});const resume=path.join(root,'resume.pdf');fs.writeFileSync(resume,await doc.save());dialog.showOpenDialog=async()=>({canceled:false,filePaths:[resume]});
 require('../.vite/build/main.js');
 app.whenReady().then(async()=>{try{
  const overlay=BrowserWindow.getAllWindows()[0];if(overlay.webContents.isLoading())await new Promise(r=>overlay.webContents.once('did-finish-load',r));assert.equal((await evalIn(overlay,`window.kite.prepareCareerJob({runId:'49bb3c28-fc8f-4545-a34c-e19db07118de',revision:1,jobKey:'invalid'})`)).ok,false,'overlay cannot prepare applications');
  await evalIn(overlay,"window.kite.openView('agents')");let panel=await until(()=>BrowserWindow.getAllWindows().find(w=>w!==overlay&&w.webContents.getURL().includes('agents')),Boolean,'Agents');await until(()=>evalIn(panel,"!!document.querySelector('.agents-heading button:not(:disabled)')"),Boolean,'ready');await click(panel,'New run');await value(panel,'[aria-label="Document task"]','career_scout','change');await value(panel,'[aria-label="Company board 1"]','fixture');await value(panel,'[aria-label="Job keywords"]','software');await click(panel,'Start run');await until(()=>evalIn(panel,"[...document.querySelectorAll('button')].some(b=>b.textContent==='Approve job discovery'&&!b.disabled)"),Boolean,'discovery approval');assert.equal(fixture.calls.length,0);
  panel.close();await wait(50);await evalIn(overlay,"window.kite.openView('agents')");panel=await until(()=>BrowserWindow.getAllWindows().find(w=>w!==overlay&&w.webContents.getURL().includes('agents')),Boolean,'reopened Agents');await until(()=>evalIn(panel,"!!document.querySelector('.agents-run-item')"),Boolean,'saved run');await evalIn(panel,"document.querySelector('.agents-run-item').click()");await until(()=>evalIn(panel,"[...document.querySelectorAll('button')].some(b=>b.textContent==='Approve job discovery'&&!b.disabled)"),Boolean,'restored approval');await click(panel,'Approve job discovery');await until(()=>evalIn(panel,"document.querySelectorAll('.agents-shortlist .agents-mail-message').length"),n=>n===1,'shortlist cards');await until(()=>evalIn(panel,"[...document.querySelectorAll('button')].some(b=>b.textContent==='Prepare application'&&!b.disabled)"),Boolean,'prepare enabled');await click(panel,'Prepare application');await until(()=>evalIn(panel,"!!document.querySelector('[aria-label=\"Applicant firstName\"]')"),Boolean,'application input');
  await value(panel,'[aria-label="Applicant firstName"]','Panel');await value(panel,'[aria-label="Applicant lastName"]','Candidate');await value(panel,'[aria-label="Applicant email"]','panel@kite.test');await click(panel,'Choose PDF resume');await until(()=>evalIn(panel,"[...document.querySelectorAll('button')].some(b=>b.textContent==='Review application inputs'&&!b.disabled)"),Boolean,'resume frozen');await click(panel,'Review application inputs');await until(()=>evalIn(panel,"[...document.querySelectorAll('button')].some(b=>b.textContent==='Approve application preparation'&&!b.disabled)"),Boolean,'personal-input approval');assert.equal(fixture.submissions.length,0);await click(panel,'Approve application preparation');await until(()=>evalIn(panel,"[...document.querySelectorAll('button')].some(b=>b.textContent==='Check acknowledgement'&&!b.disabled)"),Boolean,'handoff');
  const browser=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().startsWith('https://job-boards.greenhouse.io/fixture/jobs/101'));assert.ok(browser);assert.equal(browser.isVisible(),false);assert.equal(await evalIn(browser,'typeof window.kite+":"+typeof require'),'undefined:undefined');assert.equal(await evalIn(browser,'document.querySelector("input[name=email]").value'),'panel@kite.test');assert.equal(fixture.submissions.length,0);await click(panel,'Open application browser');await until(()=>browser.isVisible(),Boolean,'explicit takeover');fs.mkdirSync('out',{recursive:true});fs.writeFileSync('out/career-panel.png',(await panel.webContents.capturePage()).toPNG());fs.writeFileSync('out/career-browser.png',(await browser.webContents.capturePage()).toPNG());await until(()=>evalIn(panel,"[...document.querySelectorAll('button')].some(b=>b.textContent==='Finish preparation without submitting'&&!b.disabled)"),Boolean,'finish ready');await click(panel,'Finish preparation without submitting');await until(()=>evalIn(overlay,'window.kite.backgroundSnapshot()'),s=>s.runs.some(r=>r.workflow==='job_application'&&r.status==='succeeded'),'prepared completion');assert.equal(fixture.submissions.length,0);assert.deepEqual(errors,[]);console.log('PASS career panel: private IPC, board/filter composer, approval close/reopen, shortlist cards/PDF, native resume selection, reviewed personal inputs, isolated standard-field staging, explicit browser takeover and preparation-only completion');fixture.close();clearTimeout(deadline);app.quit();
 }catch(e){console.error(e);fixture.close();clearTimeout(deadline);app.exit(1);}});
})().catch(e=>{console.error(e);clearTimeout(deadline);app.exit(1);});
