// Real packaged composition, preload, React and trusted IPC; public GET traffic uses a local fixture.
const { app, BrowserWindow, dialog } = require('electron');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path'), assert = require('node:assert/strict');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'kite-schedules-panel-'));
app.setPath('userData', root); process.env.KITE_TEST_MODE = '1';
app.on('browser-window-created', (_e,w) => w.setOpacity(0)); const errors = []; dialog.showErrorBox = (t,m) => errors.push(`${t}: ${m}`);
const realNow = Date.now; let offset = 0; Date.now = () => realNow() + offset;
let reads = 0; const nativeFetch = globalThis.fetch.bind(globalThis);
globalThis.fetch = (url,opt) => new URL(url).hostname === 'boards-api.greenhouse.io' ? (reads++, Promise.resolve(new Response(JSON.stringify({ jobs: [{ id: 1, title: 'Synthetic scheduled engineer', content: 'Local fixture' }] })))) : nativeFetch(url,opt);
const evalIn = (w,code) => w.webContents.executeJavaScript(code), wait = ms => new Promise(r => setTimeout(r,ms));
const until = async (read, test, label) => { for(let i=0;i<700;i++) { const value = await read(); if(test(value)) return value; await wait(50); } throw Error('Timed out: '+label); };
const click = (w,text) => evalIn(w, `(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(text)});if(!b||b.disabled)throw Error('Missing/disabled '+${JSON.stringify(text)});b.click();})()`);
const value = (w,selector,v) => evalIn(w, `(()=>{const e=document.querySelector(${JSON.stringify(selector)});Object.getOwnPropertyDescriptor(e.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(v)});e.dispatchEvent(new Event(e.tagName==='SELECT'?'change':'input',{bubbles:true}));})()`);
const deadline = setTimeout(() => { console.error('Schedules panel timed out'); app.exit(1); }, 100000);
require('../.vite/build/main.js');
app.whenReady().then(async () => { try {
  const overlay = BrowserWindow.getAllWindows()[0]; if(overlay.webContents.isLoading()) await new Promise(r => overlay.webContents.once('did-finish-load',r));
  const helper = await evalIn(overlay, `window.kite.saveBackgroundAgent({name:'Forbidden',instructions:'',workflow:'text_pdf',style:'readable'})`); assert.equal(helper.ok,false);
  await evalIn(overlay, "window.kite.openView('agents')"); let panel = await until(() => BrowserWindow.getAllWindows().find(w => w!==overlay && w.webContents.getURL().includes('agents')), Boolean, 'panel');
  await until(() => evalIn(panel, "!!document.querySelector('.agents-heading button:not(:disabled)')"), Boolean, 'ready');
  const saved = await evalIn(panel, `window.kite.saveBackgroundAgent({name:'Scheduled fixture scout',instructions:'',workflow:'career_scout',style:'readable',career:{boards:[{provider:'greenhouse',board:'fixture',region:'global'}],keywords:'',location:'',maxJobs:4}})`); assert.equal(saved.ok,true);
  await click(panel,'Schedules'); await click(panel,'New schedule'); await value(panel,'[aria-label="Scheduled helper"]',saved.agentId); await value(panel,'[aria-label="Schedule repeat"]','interval'); await value(panel,'[aria-label="Schedule minutes"]','15');
  assert.equal(await evalIn(panel,"[...document.querySelectorAll('button')].find(b=>b.textContent==='Create schedule').disabled"),true,'explicit recurring consent is required');
  await evalIn(panel,"document.querySelector('[aria-label=\"Approve recurring reads\"]').click()"); await click(panel,'Create schedule');
  const state = await until(() => evalIn(panel,'window.kite.backgroundSnapshot()'),s=>s.schedules.length===1,'saved schedule'); const schedule = state.schedules[0]; assert.equal(reads,0);
  assert.equal((await evalIn(overlay, `window.kite.controlAgentSchedule({id:'${schedule.id}',revision:${schedule.revision},action:'pause'})`)).ok,false,'overlay cannot alter recurring authority');
  assert.equal(await evalIn(overlay,`window.kite.agentScheduleHistory({id:'${schedule.id}'})`),null,'private schedule history denied');
  panel.close(); await wait(50); await evalIn(overlay,"window.kite.openView('agents')"); panel = await until(() => BrowserWindow.getAllWindows().find(w => w!==overlay && w.webContents.getURL().includes('agents')),Boolean,'reopened'); await until(()=>evalIn(panel,"!!document.querySelector('.agents-heading button:not(:disabled)')"),Boolean,'reopened ready'); await click(panel,'Schedules'); await until(()=>evalIn(panel,"document.querySelectorAll('.agents-schedule').length"),n=>n===1,'persisted schedule');
  offset = 16 * 60000;
  await until(()=>evalIn(panel,'window.kite.backgroundSnapshot()'),s=>s.runs.some(r=>r.schedule&&r.status==='succeeded'),'scheduled result'); assert.equal(reads,1);
  offset += 15 * 60000;
  const quiet = await until(()=>evalIn(panel,'window.kite.backgroundSnapshot()'),s=>s.runs.some(r=>r.schedule&&r.unchanged),'quiet result'); assert.equal(reads,2); assert.equal(quiet.runs.find(r=>r.unchanged).artifacts.length,0);
  await evalIn(panel,"[...document.querySelectorAll('.agents-schedules button')].find(b=>b.textContent==='History').click()"); await until(()=>evalIn(panel,"document.querySelectorAll('.agents-schedule-history button').length"),n=>n===2,'check history');
  fs.mkdirSync('out',{recursive:true}); fs.writeFileSync('out/schedules-panel.png',(await panel.webContents.capturePage()).toPNG());
  await click(panel,'Pause future checks'); await until(()=>evalIn(panel,"[...document.querySelectorAll('button')].some(b=>b.textContent==='Review recurring access')"),Boolean,'paused'); await click(panel,'Review recurring access'); await click(panel,'Approve and enable recurring checks');
  await until(()=>evalIn(panel,"[...document.querySelectorAll('button')].some(b=>b.textContent==='Pause future checks')"),Boolean,'renewed');
  await click(panel,'Latest check'); await until(()=>evalIn(panel,"!!document.querySelector('.agents-detail header')"),Boolean,'selected check'); assert.ok((await evalIn(panel,"document.querySelector('.agents-detail').textContent")).includes('No changes'));
  assert.deepEqual(errors,[]); clearTimeout(deadline); Date.now=realNow;
  console.log('PASS schedules panel: explicit recurring consent, frozen scope, private IPC, close/reopen, real timer dispatch, quiet checks, history, pause, renewed approval and selected-run details'); app.quit();
} catch(error) { console.error(error); clearTimeout(deadline); Date.now=realNow; app.exit(1); } });
