import type { ScreenBounds } from './types';
/**
 * "Do it for me" tasks: shared, pure pieces. Kite operates one app through UI Automation patterns and
 * keyboard input only; it never moves the pointer. Summaries and risk checks are deterministic (ADR 008),
 * so the model can never phrase its way past a confirmation.
 */
export const maxTaskSteps = 15;
export type TaskScope = 'task' | 'once';
export type TaskStatus = 'starting' | 'thinking' | 'acting' | 'approval' | 'paused' | 'asking' | 'done' | 'failed' | 'stopped';
export interface TaskLogEntry { text: string; ok: boolean }
/** Everything the overlay needs to draw the task card and point at the control being used. Rectangles are global DIP. */
export interface TaskView {
  id: number; goal: string; app: string; status: TaskStatus;
  step: number; budget: number; scope: TaskScope;
  /** The current or proposed action, in words generated by code. */
  action: string | null;
  /** Why this step needs the user's OK, when it does. */
  risk: string | null;
  message: string;
  target: ScreenBounds | null; display: ScreenBounds | null;
  log: TaskLogEntry[];
  /** Present for a job (an errand in a browser): its phases, the page URL, and the options of an open choice. */
  job?: import('./job').JobView | null;
}
export const taskActions = ['pause', 'resume', 'stop', 'allow', 'allowAll', 'skip'] as const;
export type TaskAction = typeof taskActions[number];

/** One control from the task sidecar's snapshot, in global DIP. `ref` indexes that snapshot only. */
export interface AgentElement {
  ref: number; name: string; role: string; automationId: string; help: string; enabled: boolean; layer: number; rect: ScreenBounds;
  value?: string; focused?: boolean; selected?: boolean; expanded?: boolean; toggled?: boolean; readOnly?: boolean; password?: boolean;
  patterns: string[];
}
export interface AgentWindow { hwnd: number; title: string; process: string; pid: number; rect: ScreenBounds; foreground?: boolean }
export interface AgentSnapshot { seq: number; window: AgentWindow; layers: { layer: number; title: string; main?: boolean }[]; elements: AgentElement[] }

/** What the model may ask for, after validation. */
export type AgentAction =
  | { type: 'click'; ref: number }
  | { type: 'type_text'; ref?: number; text: string; replace?: boolean; submit?: boolean }
  | { type: 'press_keys'; keys: string; times?: number }
  | { type: 'scroll'; ref: number; direction: 'up' | 'down' | 'left' | 'right' }
  | { type: 'wait'; seconds: number }
  | { type: 'look' }
  | { type: 'ask_user'; question: string }
  | { type: 'go_to'; url: string }
  | { type: 'find'; text: string }
  | { type: 'ask_choice'; question: string; options: { label: string; detail?: string; ref?: number }[] }
  | { type: 'next_phase'; summary: string }
  | { type: 'done'; summary: string }
  | { type: 'fail'; reason: string };

// Virtual-key codes. The Windows key is deliberately absent: system shortcuts are out of reach.
const named: Record<string, number> = {
  enter: 0x0d, return: 0x0d, tab: 0x09, escape: 0x1b, esc: 0x1b, backspace: 0x08, delete: 0x2e, del: 0x2e, space: 0x20, spacebar: 0x20,
  up: 0x26, down: 0x28, left: 0x25, right: 0x27, home: 0x24, end: 0x23, pageup: 0x21, pagedown: 0x22, insert: 0x2d,
  plus: 0xbb, minus: 0xbd, comma: 0xbc, period: 0xbe, slash: 0xbf,
};
const modifierCodes = { ctrl: 0x11, shift: 0x10, alt: 0x12 } as const;
export type Modifier = keyof typeof modifierCodes;
export interface KeyChord { key: string; vk: number; modifiers: Modifier[] }
/** "Ctrl+Shift+S", "enter", "Alt+F4", "PageDown". Returns null for anything outside the allowlist. */
export function parseKeys(input: string): KeyChord | null {
  const parts = input.trim().toLowerCase().replace(/\s*\+\s*/g, '+').replace(/\s+/g, '').split('+').filter(Boolean);
  if (!parts.length || parts.length > 4) return null;
  const modifiers: Modifier[] = [];
  for (const part of parts.slice(0, -1)) {
    const name = part === 'control' ? 'ctrl' : part;
    if (!(name in modifierCodes) || modifiers.includes(name as Modifier)) return null;
    modifiers.push(name as Modifier);
  }
  const key = parts.at(-1).replace(/^(arrow)(up|down|left|right)$/, '$2').replace(/^pgup$/, 'pageup').replace(/^pgdn$/, 'pagedown');
  let vk: number | undefined = named[key];
  if (vk === undefined && /^[a-z0-9]$/.test(key)) vk = key.toUpperCase().charCodeAt(0);
  const f = key.match(/^f([1-9]|1[0-2])$/);
  if (vk === undefined && f) vk = 0x6f + Number(f[1]);
  if (vk === undefined) return null;
  const order: Modifier[] = ['ctrl', 'shift', 'alt'];
  return { key, vk, modifiers: order.filter(m => modifiers.includes(m)) };
}
export const modifierVk = (m: Modifier) => modifierCodes[m];
export function chordLabel(chord: KeyChord) {
  const key = chord.key.length === 1 ? chord.key.toUpperCase() : chord.key.replace(/^(f\d+)$/, s => s.toUpperCase()).replace(/^pageup$/, 'Page Up').replace(/^pagedown$/, 'Page Down').replace(/^./, c => c.toUpperCase());
  return [...chord.modifiers.map(m => m[0].toUpperCase() + m.slice(1)), key].join('+');
}
const clip = (s: string, n = 60) => { const t = s.replace(/\s+/g, ' ').trim(); return t.length > n ? t.slice(0, n) + '…' : t; };
const roleName = (role: string) => role.replace(/([a-z])([A-Z])/g, '$1 $2').toLowerCase();
export const describeElement = (e: Pick<AgentElement, 'name' | 'role' | 'automationId'>) =>
  e.name.trim() ? `“${clip(e.name, 50)}” ${roleName(e.role)}` : `the unlabeled ${roleName(e.role)}${e.automationId ? ` (${clip(e.automationId, 30)})` : ''}`;
/** The words shown on the card and in the audit log for an action. Never model-authored prose. */
export function describeAction(action: AgentAction, element?: AgentElement): string {
  switch (action.type) {
    case 'click': return `Click ${element ? describeElement(element) : 'a control'}`;
    case 'type_text': return `${action.replace ? 'Replace the text in' : 'Type into'} ${element ? describeElement(element) : 'the focused field'}: “${clip(action.text)}”${action.submit ? ', then press Enter' : ''}`;
    case 'press_keys': { const chord = parseKeys(action.keys); return `Press ${chord ? chordLabel(chord) : action.keys}${(action.times ?? 1) > 1 ? ` ×${action.times}` : ''}`; }
    case 'scroll': return `Scroll ${action.direction} in ${element ? describeElement(element) : 'the window'}`;
    case 'wait': return `Wait ${action.seconds} s`;
    case 'look': return 'Look at the window';
    case 'ask_user': return 'Ask you a question';
    case 'go_to': { let shown = action.url; try { const u = new URL(action.url); shown = u.hostname.replace(/^www\./, '') + (u.pathname === '/' ? '' : u.pathname); } catch { /* shown as given */ } return `Go to ${clip(shown, 70)}`; }
    case 'find': return `Look for “${clip(action.text, 40)}” on the page`;
    case 'ask_choice': return 'Ask you to choose';
    case 'next_phase': return 'Move to the next part of the job';
    case 'done': return 'Finish';
    case 'fail': return 'Give up';
  }
}

const riskyLabel = /\b(send|submit|delete|remove|erase|discard|trash|purchase|buy|pay|payment|checkout|check out|place order|order now|book now|confirm|uninstall|install|format|reset|restore defaults|sign out|log ?out|publish|post|share|transfer|withdraw|overwrite|replace all|empty|permanently|don'?t save|do not save|close without saving|unsubscribe|deactivate|revoke|accept|agree|restart|shut ?down|run|execute)\b/i;
const riskyDialog = /\b(delete|deleted|permanently|overwrite|replace|remove|discard|lose|lost|cannot be undone|can'?t be undone|irreversible|erase|format|send|pay|purchase)\b/i;
const confirmLabel = /^(ok|okay|yes|yes to all|continue|proceed|confirm|allow|go|do it)$/i;
const terminals = /^(windowsterminal|wt|cmd|powershell|pwsh|conhost|openconsole|wsl|bash|mintty|alacritty|wezterm-gui|putty|git-bash)$/i;
const messaging = /\b(message|messages|chat|reply|compose|comment|post|tweet|send|email|e-mail|mail|inbox|whatsapp|teams|slack|discord|telegram|signal|outlook)\b/i;
const riskyChords = new Set(['alt+f4', 'ctrl+w', 'ctrl+f4', 'ctrl+shift+w', 'shift+delete', 'ctrl+shift+delete', 'ctrl+enter', 'ctrl+p', 'ctrl+shift+enter', 'alt+s', 'ctrl+d']);
export interface RiskContext { element?: AgentElement; focused?: AgentElement; process: string; title: string; dialogText: string }
/**
 * Why an action needs the user's OK even inside an approved task, or null. Deterministic and deliberately
 * cautious: it reads labels and dialog text only as keywords, never as instructions.
 */
export function assessRisk(action: AgentAction, context: RiskContext): string | null {
  const keyboard = action.type === 'type_text' || action.type === 'press_keys';
  if (keyboard && terminals.test(context.process)) return 'This is a terminal, where typing and Enter can run commands.';
  if (action.type === 'click' && context.element) {
    // Icon-only buttons often carry only an automation id such as "PlaceOrderButton": split it into words.
    const e = context.element, label = `${e.name} ${e.help} ${e.automationId.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/[_-]+/g, ' ')}`;
    if (riskyLabel.test(label)) return `${describeElement(e)} may send, delete, buy, or change something that can’t be undone.`;
    if (confirmLabel.test(e.name.trim()) && riskyDialog.test(context.dialogText)) return 'This confirms a dialog that mentions deleting, overwriting, sending, or paying.';
  }
  if (action.type === 'type_text') {
    const target = action.ref !== undefined ? context.element : context.focused;
    if (target?.password) return 'This types into a password field.';
    if (/(?:\d[ -]?){13,19}/.test(action.text)) return 'This looks like a card or account number.';
    if (action.submit && messaging.test(`${context.title} ${target?.name ?? ''} ${context.process}`)) return 'Pressing Enter here may send a message.';
  }
  if (action.type === 'press_keys') {
    const chord = parseKeys(action.keys); if (!chord) return null;
    const combo = [...chord.modifiers, chord.key].join('+');
    if (riskyChords.has(combo)) return `${chordLabel(chord)} can close, send, print, or delete.`;
    const focus = context.focused;
    if (chord.key === 'enter' && !chord.modifiers.length && (messaging.test(`${context.title} ${focus?.name ?? ''} ${context.process}`) || (focus && riskyLabel.test(focus.name))))
      return 'Pressing Enter here may send or submit something.';
    if (chord.key === 'delete' && focus && ['ListItem', 'TreeItem', 'DataItem'].includes(focus.role)) return 'Delete on a selected item may remove it.';
  }
  return null;
}

/** Deterministic task controls; anything else goes to the model (or answers the task's question). */
export function classifyTaskCommand(text: string): TaskAction | 'new-request' {
  const s = text.toLowerCase().trim().replace(/’/g, "'").replace(/[.!?,]+/g, '').replace(/\s+/g, ' ').replace(/^(ok|okay|kite|hey kite) /, '').replace(/ please$/, '');
  if (/^(stop|stop it|stop the task|cancel|cancel (it|that|the task)|abort|quit|never ?mind|forget it|that's enough|stop doing that)$/.test(s)) return 'stop';
  if (/^(wait|hold on|hang on|pause|pause (it|the task)|one sec(ond)?|just a (sec|second|moment|minute))$/.test(s)) return 'pause';
  if (/^(continue|resume|go on|keep going|carry on|i'm done|i'm back|ready|go ahead and continue)$/.test(s)) return 'resume';
  if (/^(allow all|allow the rest|yes to all|do the rest|allow everything|go ahead with the rest|don't ask again)$/.test(s)) return 'allowAll';
  if (/^(yes|yeah|yep|sure|do it|go ahead|okay|ok|allow|allow it|allow once|approve|approved)$/.test(s)) return 'allow';
  if (/^(no|nope|skip|skip (it|that)|don't|do not|not that|deny)$/.test(s)) return 'skip';
  return 'new-request';
}

/** Controls for the model, most useful first: dialogs and popups, then focus, then named controls. */
export function formatSnapshot(snapshot: AgentSnapshot, limit = 220, budget = 14000): string {
  const lines: string[] = [];
  const layerTitle = new Map(snapshot.layers.map(l => [l.layer, l.title]));
  const mainLayer = snapshot.layers.find(l => l.main)?.layer ?? Math.max(...snapshot.layers.map(l => l.layer), 0);
  // Web pages repeat themselves: a product is a list item, two links and a text with the same name. Keep the first link
  // and drop nearby repeats of it; text and list items that only repeat a nearby link or button go too. Buttons always
  // stay (each tile's "Add to cart" is a different product), as do short link names and the focused control.
  const key = (e: AgentElement) => `${e.layer}|${clip(e.name, 80).toLowerCase()}`;
  const anchors = new Map<string, number[]>();
  for (const e of snapshot.elements) if ((e.role === 'Hyperlink' || e.role === 'Button') && e.name.trim()) anchors.set(key(e), [...anchors.get(key(e)) ?? [], e.ref]);
  const repeat = (e: AgentElement) => {
    const near = (anchors.get(key(e)) ?? []).filter(r => r !== e.ref && Math.abs(r - e.ref) <= 6);
    if (e.focused || !near.length || e.role === 'Button') return false;
    return e.role === 'Hyperlink' ? e.name.trim().length >= 15 && near.some(r => r < e.ref) : ['Text', 'ListItem', 'DataItem'].includes(e.role);
  };
  const ordered = [...snapshot.elements].sort((a, b) => a.layer - b.layer || Number(!!b.focused) - Number(!!a.focused) || a.ref - b.ref)
    .filter(e => (e.name.trim() || e.focused || e.value || e.patterns.length) && !repeat(e));
  let current = -1, used = 0, shown = 0;
  for (const e of ordered) {
    if (shown >= limit) break;
    if (e.layer !== current) {
      current = e.layer;
      lines.push(`${e.layer === mainLayer ? 'Main window' : 'Popup or dialog'} “${clip(layerTitle.get(e.layer) || snapshot.window.title, 80)}”:`);
    }
    // A link's or page's value is its URL: long, often tracking, and not something to act on. The page URL is given once.
    const linkish = e.role === 'Hyperlink' || e.role === 'Document';
    const state = [e.focused && 'focused', e.selected && 'selected', e.toggled === true && 'checked', e.toggled === false && e.role === 'CheckBox' && 'unchecked',
      e.expanded === true && 'expanded', e.expanded === false && 'collapsed', !e.enabled && 'disabled', e.readOnly && !linkish && 'read-only', e.password && 'password'].filter(Boolean);
    const value = e.password || (linkish && /^[a-z][a-z0-9+.-]*:/i.test(e.value ?? '')) ? '' : e.value ? ` = “${clip(e.value, 120)}”` : '';
    const line = `[${e.ref}] ${e.role} “${clip(e.name, 80)}”${value}${state.length ? ` (${state.join(', ')})` : ''}`;
    if (used + line.length > budget) break;
    lines.push(line); used += line.length + 1; shown++;
  }
  if (ordered.length > shown) lines.push(`…${ordered.length - shown} more controls not shown; scroll or open menus to reach others.`);
  return lines.join('\n');
}
