// Build-time only: Tabler SVGs become sampled pen paths, with no SVG or Tabler runtime dependency.
const { app, BrowserWindow } = require('electron');
const fs = require('node:fs'), path = require('node:path');
const names = ['user','users','device-laptop','device-mobile','server','database','cloud','lock','key','file','settings','list','world',
  'browser','api','network','router','wifi','mail','message','shield','shield-check','fingerprint','cookie','link','code','terminal','brand-react',
  'cpu','device-desktop','plug','bolt','battery','clock','calendar','git-branch','git-merge','git-commit','folder','folder-open','download','upload',
  'search','filter','chart-line','chart-bar','chart-pie','arrows-exchange','arrow-loop-right','repeat','stack','binary-tree','sitemap','hash',
  'table','layers-linked','box','package','building','credit-card'];
app.whenReady().then(async () => {
  const win = new BrowserWindow({ show: false, webPreferences: { sandbox: true } }), icons = {};
  await win.loadURL('about:blank');
  for (const name of names) {
    const svg = fs.readFileSync(path.join(__dirname, '..', 'node_modules/@tabler/icons/icons/outline', name + '.svg'), 'utf8');
    icons[name] = await win.webContents.executeJavaScript(`(() => { document.body.innerHTML = ${JSON.stringify(svg)};
      return [...document.querySelectorAll('path:not([stroke="none"]),circle,ellipse,line,polyline,polygon,rect')].map(e => {
        const length = e.getTotalLength(), count = Math.max(2, Math.ceil(length / 1.5));
        return Array.from({length:count+1},(_,i)=>{const p=e.getPointAtLength(length*i/count);return {x:Math.round(p.x*100)/100,y:Math.round(p.y*100)/100};}); }); })()`);
  }
  fs.writeFileSync(path.join(__dirname, '../src/shared/boardIcons.ts'), '// Generated by scripts/board-icons.cjs. Tabler Icons, MIT; see assets/licenses/tabler.txt.\nexport const boardIcons: Record<string, { x: number; y: number }[][]> = ' + JSON.stringify(icons) + ';\n');
  fs.mkdirSync(path.join(__dirname,'../assets/licenses'),{recursive:true});
  fs.copyFileSync(path.join(__dirname,'../node_modules/@tabler/icons/LICENSE'),path.join(__dirname,'../assets/licenses/tabler.txt'));
  win.destroy(); console.log(`Generated ${names.length} Tabler pen icons.`); app.quit();
}).catch(error => { console.error(error.message); app.exit(1); });
