// Deterministic teaching fixtures and gallery input. Provider clarity remains a separate human comparison.
require('../tests/register.cjs');const fs=require('node:fs'),path=require('node:path');
const {compileScript}=require('../src/shared/board/compile.ts'),{formulaPaths,closeMathWorker}=require('../src/main/board/math.ts'),{elkLayout,closeElkWorker}=require('../src/main/board/elk.ts');
const {lessonMetrics,referenceDisplay}=require('../src/shared/boardMetrics.ts'),{applyBeat,lintScene,panelSize}=require('../src/shared/board.ts');
const array={version:2,title:'Sort an array',family:'data',collection:'array',mode:'new',nodes:[{id:'a',label:'7',index:0},{id:'b',label:'3',index:1},{id:'c',label:'5',index:2}],edges:[],beats:[
 {say:'The array contains seven, three and five.',reveal:['a','b','c'],cues:{a:'seven',b:'three',c:'five'}},
 {say:'Swap seven and three so the smaller value comes first.',reveal:[],changes:[{kind:'swap',a:'a',b:'b'}],effects:[{kind:'pulse',ids:['a','b']}]},
 {say:'Three is now first.',reveal:[],highlight:['b'],ask:'Which two values should we swap next?'},
 {say:'Swap seven and five. The array is now sorted.',reveal:[],changes:[{kind:'swap',a:'a',b:'c'}]},
 {say:'The sorted values are three, five, seven.',reveal:[],recap:true,highlight:['a','b','c']}]};
const fixtures=[array,
 {version:2,title:'A pointer traverses a linked list',family:'data',collection:'linked-list',mode:'new',nodes:[{id:'a',label:'10'},{id:'b',label:'20'},{id:'c',label:'30'},{id:'p',label:'current',role:'pointer',relative:'a',side:'below'}],edges:[{id:'ab',from:'a',to:'b',label:'next'},{id:'bc',from:'b',to:'c',label:'next'},{id:'ref',from:'p',to:'a'}],beats:[{say:'Current points to the first node.',reveal:['a','b','c','p','ab','bc','ref']},{say:'Move current to the next node.',reveal:[],changes:[{kind:'move',id:'p',relative:'b',side:'below'}]},{say:'Follow next until the final node.',reveal:[],changes:[{kind:'move',id:'p',relative:'c',side:'below'}],recap:true,highlight:['c']}]},
 {version:2,title:'Update and erase a value',family:'data',collection:'stack',mode:'new',nodes:[{id:'a',label:'2'},{id:'b',label:'4'}],edges:[],beats:[{say:'The stack contains two and four.',reveal:['a','b']},{say:'Replace four with six.',reveal:[],changes:[{kind:'value',id:'b',value:'6'}],effects:[{kind:'badge',id:'b',number:1}]},{say:'Pop six from the stack. Two remains.',reveal:[],erase:['b'],effects:[{kind:'underline',ids:['a']},{kind:'dim',ids:['a']}],recap:true,highlight:['a']}]},
 {version:2,title:'Solve for x',family:'steps',mode:'new',nodes:[{id:'eq',label:'Start',tex:'x+2=5'},{id:'answer',label:'Subtract two',tex:'x=5-2=3'}],edges:[],beats:[{say:'Start with x plus two equals five.',reveal:['eq']},{say:'Subtract two from both sides. x equals three.',reveal:['answer']},{say:'Substitute three back in: three plus two equals five.',reveal:[],recap:true,highlight:['eq','answer']}]},
 {version:2,title:'The parabola y = x²',family:'plot',mode:'new',nodes:[{id:'p',label:'y = x²',plot:{expression:'x^2',xmin:-3,xmax:3,ymin:-1,ymax:9,points:[{x:0,y:0}],shade:true}}],edges:[],beats:[{say:'This parabola has its minimum at zero, zero.',reveal:['p']},{say:'The shaded area lies between the curve and the x axis.',reveal:[],recap:true,highlight:['p']}]}
];
(async()=>{const runs=[];let beats=0;for(const script of fixtures){const lesson=await compileScript(script,{formula:formulaPaths,layout:elkLayout});let scene=[],clean=true;for(const beat of lesson.beats){scene=applyBeat(scene,beat);const m=lintScene(scene);if(m.overlaps||m.overflow||m.through||m.textOnLines)clean=false;beats++;}runs.push({id:script.title.toLowerCase().replace(/[^a-z0-9]+/g,'-'),family:script.family,turns:[{kind:'first',script,lesson,metrics:lessonMetrics(lesson.beats),lintClean:clean}]});}
 const providers=process.argv.includes('--providers'),models=[{model:'local:teaching-fixtures',label:'Teaching fixtures',runs,summary:{drew:runs.length,lintClean:runs.filter(r=>r.turns[0].lintClean).length/runs.length}}];
 if(providers){const report=JSON.parse(fs.readFileSync(path.join(__dirname,'../docs/performance/whiteboard/phase3-provider-probe.json'),'utf8'));for(const m of report.models){const runs=m.runs.map(r=>({id:r.prompt,family:r.family,text:r.text,turns:[{kind:'first',...r}]}));models.push({model:m.model,label:m.model,runs,summary:{drew:runs.filter(r=>r.turns[0].lesson).length,lintClean:runs.filter(r=>r.turns[0].lintClean).length/runs.length}});}}
 let live;try{live=JSON.parse(fs.readFileSync(path.join(__dirname,'../docs/performance/whiteboard/phase3-live.json'),'utf8'));}catch{/* Live measurement is optional and never inferred. */}
 const result={phase:3,updated:new Date().toISOString(),display:referenceDisplay,panel:panelSize(referenceDisplay),about:providers?'Five deterministic teaching fixtures plus three targeted fresh probes on each of three providers. This is not the full golden set or a scored clarity comparison.':'Deterministic local teaching fixtures, not provider generations. Synthetic renderer checks are in phase3-renderer.json; real audio measurements are in phase3-live.json.',models,beatCount:models.reduce((n,m)=>n+m.runs.reduce((s,r)=>s+(r.turns[0].lesson?.beats.length??0),0),0),fixtureBeatCount:beats,gate:{liveWordSync:live?.gates.wordSync?'passed six-cue live fixture sample':'pending',liveDeadAir:live?.gates.deadAir?'passed three-beat live fixture sample':'pending',providerClarity:'pending human comparison'}};
 const file=path.join(__dirname,`../docs/performance/whiteboard/${providers?'phase3-gallery':'phase3-fixtures'}.json`);fs.writeFileSync(file,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({boards:models.reduce((n,m)=>n+m.runs.length,0),fixtureBeats:beats,lintClean:models[0].summary.lintClean,file}));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{closeMathWorker();closeElkWorker();});
