// Generates src/shared/boardFont.ts: Excalifont's advance widths, measured by Chromium itself (the renderer that draws
// the board), so main's layout and the overlay agree on how wide every label is. Run after changing the bundled font:
//   npx electron scripts/font-metrics.cjs
const { app, BrowserWindow } = require('electron');
const fs = require('node:fs'), path = require('node:path'), os = require('node:os');
const root = path.join(__dirname, '..'), fonts = path.join(root, 'assets', 'fonts', 'excalifont');
// The code points Excalifont covers that labels use: Latin, Latin-1, Latin Extended-A, Greek and Cyrillic.
const ranges = [[0x20, 0x17f], [0x384, 0x3cf], [0x400, 0x45f]];
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'kite-font-metrics-'));
app.setPath('userData', temporary);
app.on('window-all-closed', () => {});
app.whenReady().then(async () => {
  let code = 0;
  try {
    const faces = fs.readdirSync(fonts).filter(f => f.endsWith('.woff2')).sort()
      .map(f => `@font-face { font-family: Excalifont; src: url("${path.join(fonts, f).replace(/\\/g, '/')}") format("woff2"); }`).join('\n');
    const page = path.join(temporary, 'measure.html');
    fs.writeFileSync(page, `<!doctype html><meta charset="utf-8"><style>${faces}</style><body></body>`);
    const win = new BrowserWindow({ show: false, webPreferences: { offscreen: true, webSecurity: false } });
    await win.loadFile(page);
    const result = await win.webContents.executeJavaScript(`(async () => {
      const ranges = ${JSON.stringify(ranges)}, size = 1000;
      const all = ranges.flatMap(([a, b]) => Array.from({ length: b - a + 1 }, (_, i) => String.fromCodePoint(a + i))).join('');
      await document.fonts.load(size + 'px Excalifont', all);
      const ctx = document.createElement('canvas').getContext('2d'); ctx.font = size + 'px Excalifont';
      const covered = c => document.fonts.check(size + 'px Excalifont', c);
      const widths = ranges.map(([a, b]) => [a, Array.from({ length: b - a + 1 }, (_, i) => { const c = String.fromCodePoint(a + i); return Math.round(ctx.measureText(c).width); })]);
      const m = ctx.measureText('Hxg');
      return { widths, loaded: [...document.fonts].filter(f => f.status === 'loaded').length, ascent: Math.round(m.fontBoundingBoxAscent), descent: Math.round(m.fontBoundingBoxDescent) };
    })()`);
    if (!result.loaded) throw new Error('Excalifont did not load');
    // Unknown characters (other scripts fall back to the handwriting stack) count as the average lowercase letter.
    const lower = result.widths[0][1].slice(0x61 - 0x20, 0x7a - 0x20 + 1), fallback = Math.round(lower.reduce((a, b) => a + b, 0) / lower.length);
    const out = `// Generated by scripts/font-metrics.cjs from assets/fonts/excalifont (Excalifont Regular, OFL-1.1). Do not edit.
/** Advance widths in thousandths of an em, measured by Chromium, for runs of code points starting at each \`from\`. */
export const excalifontWidths: { from: number; widths: number[] }[] = [
${result.widths.map(([from, widths]) => `  { from: 0x${from.toString(16)}, widths: [${widths.join(',')}] },`).join('\n')}
];
/** For characters outside those runs. */
export const excalifontFallbackWidth = ${fallback};
`;
    fs.writeFileSync(path.join(root, 'src', 'shared', 'boardFont.ts'), out);
    console.log(`Wrote src/shared/boardFont.ts (${result.widths.reduce((n, [, w]) => n + w.length, 0)} widths, ${result.loaded} faces loaded, fallback ${fallback}).`);
  } catch (error) { console.error(error); code = 1; }
  finally { try { fs.rmSync(temporary, { recursive: true, force: true }); } catch { /* still in use */ } app.exit(code); }
});
